cursor #171d1e
cursor_text_color #3f484a

foreground            #171d1e
background            #f5fafc
selection_foreground  #ffffff
selection_background  #00bcd4
url_color             #0097a7

color0   #0e1416
color1   #9e0037
color2   #007d0b
color3   #c8ba00
color4   #009eaf
color5   #adf7ff
color6   #0097a7
color7   #2b2e2e
color8   #868d8d
color9   #d62050
color10  #00b710
color11  #d9c900
color12  #00adc0
color13  #adf7ff
color14  #6cced9
color15  #f0f9fa
