CompileFlags:                     # Tweak the parse settings
  Add: [-Werror -Wall -Wextra -Wpedantic -Wmisleading-indentation -Wunused
    -Wuninitialized -Wshadow -Wconversion]
  # Add: [-Wall, -Wextra, -std=c++26, -stdlib=libc++]
  Remove: []
  # Compiler: g++
  # Compiler: clang++             # Change argv[0] of compile flags to `clang++`

Index:
  Background: Skip     # Disable slow background indexing of these files.
  StandardLibrary: false

Style:
  AngledHeaders: 
    - third-party/.*
    - 3rdparty/.*

Diagnostics:
  ClangTidy:
    Add:
      - bugprone-*
      - cppcoreguidelines-*
      - google-readability-*
      - performance-*
      - portability-*
      - modernize-*
      - readability-*
    Remove:
      - bugprone-easily-swappable-parameters
      - readability-identifier-length
      # - cppcoreguidelines-pro-bounds-constant-array-index
      # - readability-qualified-auto
      # - readability-isolate-declaration
      - cppcoreguidelines-init-variables
      # - cppcoreguidelines-avoid-const-or-ref-data-members
      - cppcoreguidelines-avoid-do-while
      # - cppcoreguidelines-macro-usage
      - modernize-use-std-print
      - modernize-use-trailing-return-type
      # - cppcoreguidelines-avoid-magic-numbers
      # - readability-magic-numbers
    CheckOptions:
      readability-identifier-naming.VariableCase: lower_case
    FastCheckFilter: Loose
  UnusedIncludes: None
  Includes:
    AnalyzeAngledIncludes: No

Completion:
  AllScopes: No
  ArgumentLists: FullPlaceholders

InlayHints:
  BlockEnd: false
  Designators: true
  Enabled: true
  ParameterNames: true
  DeducedTypes: true
  DefaultArguments: true
  TypeNameLimit: 24

Hover:
  ShowAKA: false

SemanticTokens:
  DisabledKinds: []
  DisabledModifiers: []

Documentation:
  CommentFormat: Markdown
